/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./frontend/**/*.{js,ts,jsx,tsx}",
    "./frontend/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    // Ensure common utility classes are always included
    'bg-slate-900',
    'bg-slate-800',
    'bg-slate-700',
    'bg-slate-600',
    'text-white',
    'text-slate-400',
    'text-slate-300',
    'text-blue-400',
    'text-green-400',
    'text-red-400',
    'text-amber-400',
    'text-purple-400',
    'text-orange-400',
    'bg-blue-600',
    'bg-green-600',
    'bg-red-600',
    'bg-amber-600',
    'bg-purple-600',
    'bg-orange-600',
    'hover:bg-blue-700',
    'hover:bg-green-700',
    'hover:bg-red-700',
    'hover:bg-slate-700',
    'border-slate-700',
    'border-slate-600',
    'border-blue-500',
    'rounded-xl',
    'rounded-lg',
    'p-4',
    'p-3',
    'px-3',
    'py-2',
    'mb-2',
    'mb-3',
    'mt-2',
    'mt-3',
    'space-y-4',
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:grid-cols-4',
    'gap-3',
    'gap-4',
    'flex',
    'items-center',
    'justify-between',
    'font-semibold',
    'font-bold',
    'text-sm',
    'text-xs',
    'text-lg',
    'text-2xl',
    'w-full',
    'outline-none',
    'focus:ring-1',
    'focus:ring-blue-500',
    'transition-colors',
    'cursor-pointer',
    'disabled:opacity-50',
    'disabled:cursor-not-allowed'
  ]
}